<h2>edit</h2>

<p>users id:<?php echo $user->id; ?></p>
<p>users name:<?php echo $user->name; ?></p>
<p>users email:<?php echo $user->email; ?></p>


<?php echo $this->tag->form("signup/update/$user->id"); ?>
    <input type="hidden" name="id" value="<?php echo $user->id; ?>">
    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>
