<?php

echo "<h1>Hello!</h1>";


echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary']);

if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>送信</th>
            <th>削除</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <!-- $usersにuserモデルから取得したusersが入っている -->
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <td>
                  <form action="/signup/send" method="post">
                        <input type="hidden" name="id" value="<?php echo $user->id; ?>" >
                        <input type="submit" value="送信">
                  </form>
                </td>
                <td>
                  <form action="/signup/delete/<?php echo $user->id; ?>" method="post">
                        <input type="submit" value="削除">
                  </form>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
